name: Build and Push as Prerelease

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        targetplatform: [x64]
        ChannelName: [Release]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x  # Adjust the version if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true -o publish

      - name: Package
        run: Compress-Archive -Path .\publish\* -DestinationPath .\Launcher.zip

      - name: Check for existing release
        id: check_release
        run: |
          exists=$(curl -s -o /dev/null -w "%{http_code}" -H 'Authorization:***' https://api.github.com/repos/AssassinsCreedRemastered/The-Ezio-Trilogy-Launcher/releases/tags/beta)
          echo "exists=$exists" >> $GITHUB_ENV
          
      - name: Delete existing release
        if: steps.check_release.outputs.exists == '200'
        run: |
          release_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/beta | jq -r .id)
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/${release_id}"
          git push origin --delete beta

      - name: Update release asset
        id: update_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./Launcher.zip
          tag_name: beta
          target_commitish: ${{ github.event.before }}
          prerelease: true
